- content/glossary/accredited-researcher.jsonnet
- content/glossary/baw.jsonnet
- content/glossary/community-methods.jsonnet
- content/glossary/expert-group.jsonnet
- content/glossary/exploration.jsonnet
- content/glossary/git.jsonnet
- content/glossary/github.jsonnet
- content/glossary/idp.jsonnet
- content/glossary/ids.jsonnet
- content/glossary/internal-methods.jsonnet
- content/glossary/markdown.jsonnet
- content/glossary/metadata.jsonnet
- content/glossary/official-outputs.jsonnet
- content/glossary/package.jsonnet
- content/glossary/private-methods.jsonnet
- content/glossary/public-methods.jsonnet
- content/glossary/release-notes.jsonnet
- content/glossary/release.jsonnet
- content/glossary/repository.jsonnet
- content/glossary/semantic-versioning.jsonnet
- content/glossary/sensitive.jsonnet
- content/glossary/sml-team.jsonnet
- content/glossary/sml.jsonnet
- content/glossary/srs.jsonnet
- content/glossary/statistical-methods.jsonnet
- content/glossary/third-party-methods.jsonnet
- content/glossary/version-control.jsonnet
- sml_builder/glossary.py
- sml_builder/templates/glossary.html
Adds current glossary content, and adds functionality to allow for external links
> Spp 7309 glossary content

- sml_builder/templates/help-methods-request.html
removed unnecessary brackets in methods-request content.
> removed unnecessary brackets in methods-request content.

- sml_builder/templates/help-methods-request.html
Description: 
This story is about updating text in Help Centre.
> spp-7663 Update text in Help Centre

- readme.md
S3 Bucket creation section removed, freezing the site section removed, and destroying your site section removed.
Added a prerequisites section and added more troubleshooting information.
> Updated the readme file.

- content/help_centre/coding-standards.md
Updated the content for the coding standards page.
> Updated the coding standards file content within the help centre.

- sml_builder/templates/help-methods-request.html
Headers and sub headers changed in the help center and converted into twisties
> Spp7990headers

- content/methods/date-adjustment.jsonnet
- content/methods/ht-ratio-estimation.jsonnet
- content/methods/ratio-of-means.jsonnet
- content/methods/selective-editing.jsonnet
- content/methods/thousand-pound-correction.jsonnet
- content/methods/winsorisation.jsonnet
- sml_builder/templates/method.html
This ticket is to add some user friendly messaging to the frontend and to add some user guidance links.
> Smlportalgithubresourcechanges

- .github/workflows/pr-closed.yml
- .github/workflows/reusable.yml
Github actions changed to remove warning label
> updated github actions to remove warnings

- content/methods/date-adjustment.jsonnet
- content/methods/selective-editing.jsonnet
updated links for selective editing and date adjustment docs
> updated links for selective editing and date adjustment docs

- content/help_centre/view-methods.md
https://jira.ons.gov.uk/browse/SPP-8329
Help centre amended. method changed to methods
> SPP-8329-Update-Help-Centre

- sml_builder/templates/core.html
- sml_builder/templates/index.html
https://jira.ons.gov.uk/browse/SPP-8328
Text under help center amended to capitalise Methods and Library, Accessibility statement amended to Accessibility Statement
> SPP-8328-Update-Landing-Page

- sml_builder/templates/cookies.html
- sml_builder/templates/core.html
> Changed cookie headers

- content/help_centre/help_centre.json
- content/help_centre/version-methods.md
This PR covers the work needed to add Steve's version policy information
> Add how methods are versioned to the help center

- .well-known/security.txt
- sml_builder/page.py
- sml_builder/templates/security.html
security.txt file added to .well-known
app route also created to allow viability of the text via /.well-known/security.txt
> SPP-8354-add-security.txt

- content/methods/winsorisation.jsonnet
- features/ht_ratio_estimation.feature
- features/methods.feature
- features/steps/ht-ratio-estimation.py
In the methods catalogue winsorisation has been changed from complete to in development as it is lacking documentation.
I also noticed some cucumber feature tests needed updating to reflect new method titles and dropdown descriptions. So i corrected them as part of this ticket.
https://jira.ons.gov.uk/browse/SPP-8360
- [] Documentation updated where required 
**Testing**
**Deployment**
> SPP-8360-change-winsorisation-status-and-correct-tests

- content/help_centre/help_centre.json
- features/help_center.feature
- features/steps/help-centre.py
This ticket is to change the sub titles in the help center and create more behavior tests
Commenting, documentation and other unticked areas below are not complete as its not needed for a minor change
https://jira.ons.gov.uk/browse/SPP-8386
**Testing**
> SPP-8386-remove-how-to-from-help-center

- features/help_center.feature
- features/steps/help-centre.py
- sml_builder/templates/help-methods-request.html
This ticket addresses some grammar mistake and also adds a behavior tests to check the external user content for the 'how to submit a method#' page is covered by our suite
Documentation not updated as this is not needed
https://jira.ons.gov.uk/browse/SPP-8384
Please include the link to the relevant Jira ticket here for ease of cross-referencing.
**Testing**
> SPP-8384-grammer-correction-in-help-center

- features/methods.feature
- features/steps/method.py
This ticket is to add BDD Selenium tests to check the methods catalogue table headers on the methods catalogue page.
Documentation not updated as this is not needed
https://jira.ons.gov.uk/browse/SPP-8385
Please include the link to the relevant Jira ticket here for ease of cross-referencing.
**Testing**
> SPP 8385 Methods Catalogue Tests

- features/header.feature
- features/methods.feature
- sml_builder/templates/methods.html
This ticket is to change the title of the methods catalog and remove a sub title from the same page.
Tests have also been updated.
Commenting, documentation and other unticked areas below are not complete as its not needed for a minor change
https://jira.ons.gov.uk/browse/SPP-8382
**Testing**
> SPP-8382-change-title-all-methods-to-methods-catalogue

- features/cookies.feature
- features/steps/cookies.py
- features/steps/horviz-thompson-ratio-estimator.py
- features/steps/ratio-of-means.py
- features/steps/selective-editing.py
- features/steps/setupSelenium.py
- features/steps/thousand-pound-correction.py
- features/steps/winsorisation.py
- sml_builder/templates/cookies.html
This ticket addresses some poorly named test definitions and adds some behaviour tests for setting cookie preferences and changing cookie preferences
If you have not checked any of the list below explain why here.
Documentation not updated as this is not needed
https://jira.ons.gov.uk/browse/SPP-8388
Please include the link to the relevant Jira ticket here for ease of cross-referencing.
**Testing**
> Spp 8388 add cookie behaviour tests

- sml_builder/templates/help-methods-request.html
In this ticket we update/ add content to the help centre > I am an ONS internal user web page.
https://jira.ons.gov.uk/browse/SPP-8288
**Testing**
**Deployment**
**Notes**
- Code comment & documentation are not needed in this case, as we are just updating content that is displayed on the web app.
> SPP-8288-add-link-help-centre

- features/methods.feature
- sml_builder/templates/methods.html
This ticket is to cover changing the methods catalog dropdown content
Behavior tests have also been updated 
https://jira.ons.gov.uk/browse/SPP-8409
**Testing**
**Deployment**
> SPP-8409-methods-catalogue-dropdown-change

- features/steps/cookies.py
- features/steps/generic.py
- sml_builder/templates/index.html
This ticket is to cover changing the landing page title
https://jira.ons.gov.uk/browse/SPP-8410
**Testing**
**Deployment**
> SPP-8410-change-landing-page-title

- sml_builder/templates/methods.html
Removed code spec and permissions box
Behavior tests have also been added 
**Testing**
**Deployment**
> SPP-8389-Remove-code-spec-permission-box

- content/methods/date-adjustment.jsonnet
- content/methods/ht-ratio-estimation.jsonnet
- content/methods/ratio-of-means.jsonnet
- content/methods/selective-editing.jsonnet
- content/methods/thousand-pound-correction.jsonnet
- content/methods/winsorisation.jsonnet
- features/methods.feature
- features/steps/method.py
- sml_builder/method.py
- sml_builder/templates/methods.html
Removed access column from the methods table.
Behavior tests have also been updated 
**Testing**
**Deployment**
> SPP-8454-remove-access-from-methods-table

- content/accessibility/accessibility-statement.md
- features/footer.feature
- features/steps/cookies.py
- features/steps/footer.py
- features/steps/generic.py
- features/steps/header.py
- features/steps/help-centre.py
- features/steps/method.py
- features/steps/method_summary.py
- features/steps/setupSelenium.py
- readme.md
- sml_builder/glossary.py
- sml_builder/help_centre.py
- sml_builder/method.py
- sml_builder/page.py
- sml_builder/templates/about.html
- sml_builder/templates/accessibility_statement.html
- sml_builder/templates/core.html
- sml_builder/utils.py
Accessibility statement page:
- Added the route for the accessibility page
- Accessibility statement content is added to a markdown file which is taken and rendered onto the accessibility statement HTML template
About page:
- The variable assigned within the render_template method to be used in the about page HTML template was misspelled, so corrected from "page_boby" to "page_body"
- Updated the about page HTML template to reflect the variable name correction
Added generic BDD tests for all the pages within the footer section:
- Cookies page
- Accessibility Statement page
- Privacy and Data Protection Page
Extracted the _page_not_found function which is used to display a 404 status on the web page and made it into a utility function that can now be reused across the web app.
Added …
> SPP-8500-Accessibility-Page

- .github/pull_request_template.md
- readme.md
This ticket is to cover creating a new pull request template. It is a copy of the one used in CMS.
**Testing**
**Deployment**
> SPP-8362-create-a-new-pull-request-template

- content/methods/ready-to-use-methods/date-adjustment.jsonnet
The date adjustment page now has a specification link.
Code commenting, tests and documentation does not require updating.
**Testing**
> SPP-8623-specification-link-change

- sml_builder/method.py
- sml_builder/templates/methods.html
This ticket is to update the future methods content. It was originally the ticket to separate out the tables. However, business have asked for changes.
Test run and pass. Documentation and comments have not been updated as this is not necessary.
**Testing**
> Spp 8502 seperate out methods

- sml_builder/templates/methods.html
The future table disclaimer needs to be changed. This ticket adds the new disclaimer and removes the old one.
Comments and documentation not added due to low level change.
**Testing**
> SPP-8544-change-disclaimer-for-future-table

- content/methods/future-methods/ht-ratio-estimation.jsonnet
- content/methods/future-methods/ratio-of-means.jsonnet
- content/methods/future-methods/winsorisation.jsonnet
- sml_builder/templates/methods.html
Removed the method code link for all the methods in the future methods table (The code link was removed from the method summary page for each method).
Code comments and documentation update not required.
**Testing**
> SPP-8664-Remove-Method-Code-Links

- content/methods/future-methods/mean-of-ratios.jsonnet
- features/method_summary.feature
- features/methods.feature
- features/steps/method.py
Mean of ratios .jsonnet file create to display method within methods catalogue, behave tests also updated to check means of ratios exists and the data is as expected
**Testing**
> Spp 8757 add mean of ratios

- features/accessibility.feature
Amendment to previous PR to add accessibility test for the Mean of Ratios Page
**Testing**
> SPP-8757 Behave test for accessibility added 

- sml_builder/templates/method.html
This ticket is to update the version link on the method summary page to open in a new tab.
- Code refactored & updated the code to open the version link on a new tab
Documentation & code comments are not required in this instance.
**Testing**
> SPP-8836-Externalise-Link

- features/cookies.feature
- features/footer.feature
- features/steps/cookies.py
- sml_builder/templates/content/privacy.html
- sml_builder/templates/cookies.html
- sml_builder/templates/core.html
- sml_builder/templates/method.html
- sml_builder/templates/methods.html
This ticket is to update content in several areas of the website.
- Home page title updated.
- The title of the website is updated all across the website.
- Methods catalogue page, methods table title updated.
- Method summary page, GitHub resources section re-ordered.
- BDD tests updated as required.
Documentation & code comments are not required in this instance.
**Testing**
> SPP-8835-Content-Changes

- terraform/cloudfront.tf
As part of the pen test we received some low level issues that need to be corrected. This ticket is one of two to do this. 
Documentation has not been added.
Credit to @sanjeevz3009  for his help
**Testing**
> Spp-8863-missing-application-headers

- content/accessibility/accessibility-statement.md
Date format changed from 01/02/2023 to 1 February 2023 to align with standards.
No other changes to documentation or commenting needed
**Testing**
> review changes

- axeResults.json
- content/accessibility/accessibility-statement.md
- content/methods/future-methods/mean-of-ratios.jsonnet
- features/accessibility.feature
- features/method_summary.feature
- features/methods.feature
We now have the go ahead to add mean or ratios plus totals and components to the future table of the methods catalogue.
Test have been updated but comments and docs are not needed to be updated at this point.
**Testing**
> Spp 8621 8622 add new methods to portal

- ci/dev-pipeline.yml
- ci/live-pipeline.yml
- ci/tasks/build_and_deploy/deploy.sh
Amending how deploy grabs workspace name for main branches, change identical to previous fix for apply terraform
> Amendments to deploy.sh

- ci/tasks/build_and_deploy/deploy.sh
Removing line in deploy.sh that causes error in pipeline
> Removing Problem Command

- terraform/core.tf
Amending terraform role assume so all environments can run
> Amending terraform to only use variable version of deploy role

- terraform/core.tf
> Revert "Amending terraform to only use variable version of deploy role"

- ci/dev-pipeline.yml
- ci/live-pipeline.yml
- ci/tasks/terraform/apply_terraform.sh
- ci/tasks/terraform/destroy_terraform.sh
- terraform/core.tf
Terraform backend using wrong deployment role, pipeline cleanup
> Cleanup of pipelines, amended terraform s3 role

- axeResults.json
- content/methods/future-methods/totals-and-components.jsonnet
- features/method_summary.feature
- features/methods.feature
An error was made in the original PR that meant theme, language and expert group needed changing. This PR covers it.
Comments and documentation updates not needed.
**Testing**
> Spp 8622 correct totals and components

- ci/tasks/build_and_deploy/build_files.sh
Fix to build.sh to set the git user and email for both preprod and prod runs of the pipeline
> SPP-9387-Release-Versioning

- ci/live-pipeline.yml
- ci/tasks/build_and_deploy/build_files.sh
Concourse update now causes git to checkout at a specific commit rather than a branch, this causes a detached head state if you attempt to push changes to the repo
**Testing**
> Concourse issues fix

- ci/live-pipeline.yml
- ci/tasks/build_and_deploy/build_files.sh
fixes to the original script to correctly use the gpg signing key for signed commits when performing semantic releases
**Testing**
> ci: amending scripts to use signing key correctly

- content/help_centre/coding-standards.md
- features/help_center.feature
- features/steps/generic.py
- features/steps/help-centre.py
This pull request is to amend the PEP8 link in the coding standards page in order to make it more descriptive, this will enable all users to understand the purpose of the link in their journey.
Code has not been commented and documentation has not been written because it is not necessary for this PR.
**Testing**
> Add more description to the PEP8 link

- content/help_centre/github.md
- content/help_centre/version-methods.md
- sml_builder/templates/help-methods-request.html
This pull request will add more description to several links in the help centre, this will enable screen reader users to understand the purpose of the link more clearly.
**Testing**
> SPP-9549-amend-non-descriptive-links

- features/methods.feature
- sml_builder/templates/methods.html
This pull request is to change the description of a link in order to inform screen reader users that the link opens in a new window.
**Testing**
> SPP-9550-link-opens-new-window

- README.md
This PR updates the [confluence page](https://confluence.ons.gov.uk/display/ESD/Guide+on+using+pipenv%2C+pyenv%2C+poetry+and+venv) to include guidance on how to install poetry and instructions on basic usage.
This PR also updates the README.md file to reflect the changes to the confluence file.
Code has not been commented and documentation has not been written because it is not necessary for this PR.
**Testing**
> SPP-10025-update-confluence-documentation

- content/glossary/idp.jsonnet
- content/glossary/ids.jsonnet
Abbreviations of ‘IDP’ and ‘IDS’ has been used as heading and link text in the glossary which some users may not understand. This pull request will clarify the full meaning of these abbreviations.
**Testing**
> SPP-9551-clarify-abbreviations

- sml_builder/templates/help-methods-request.html
Links have been presented on the page using URL’s which do not describe the purpose of the links without the additional surrounding context on the page. This PR clarifies the purpose of this link for screen reader users.
Comments and documentation have not been provided since they are not necessary for this PR.
**Testing**
> SPP-9545-amend-IBM-BAW-link

- sml_builder/templates/method.html
The links below the 'GitHub resources' heading are non-descriptive for screen reader users navigating out of the context of the page. This PR will provide more detail in the link descriptions in order to make the purpose of the links clearer.
Comments and documentation have not been provided because it is not necessary for this PR.
**Testing**
> SPP-9544-amend-github-resources-links

- axeResults.json
- features/methods.feature
- features/steps/method.py
- features/steps/method_summary.py
- sml_builder/templates/method.html
- sml_builder/templates/methods.html
The ‘v1.0.0’ link is non-descriptive for screen reader users navigating out of the context of the page as it is not clear what the purpose of the link is and what will be opened upon activation of the link. This PR provides additional information for screen reader users about the purpose of the link with text that is visually hidden from sighted users.
Code has not been commented and documentation has not been provided because it is not necessary for this PR.
**Testing**
> SPP-9541-Amend-Selective-Edit

- sml_builder/templates/methods.html
When the page is set to reflow settings (1280px at 400% magnification) users are unable to view and interact with the content effectively. This PR will make use of the ONS Design System's 'Responsive' table variant in order to ensure that all of the table's content can be viewed at the same time when reflow settings are used.
Comments and documentation have not been provided as they are not necessary for this PR
**Testing**
> SPP-9453-adjust-content-for-reflow

- .github/pull_request_template.md
- ci/live-pipeline.yml
Amending github template to mention that a fix, feat or BREAKING_CHANGE tag is needed on at least one commit of the PR and that commit message should be copied if the the pr is squashed and merged
**Testing**
> Fix GitHub template

- .github/pull_request_template.md
Example amending commit message of previous pr with rebase
**Testing**
Usage
E.G feat: adding method x to future …
> Amend commit message

- axeResults.json
- content/methods/ready-to-use-methods/totals-and-components.jsonnet
- features/method_summary.feature
- features/methods.feature
This ticket is to cover the work to move the Totals and Components method across to the ready table.
Tests and documentation has been updated.
**Testing**
Usage
E.G feat: adding …
> SPP-8772-add-tac-to-ready-table

- README.md
- ci/live-pipeline.yml
- ci/rollback-environment.yml
- ci/tasks/build_and_deploy/build_files.sh
Draft to test roll back functionality at branch level
**Testing**
Usage
E.G feat: adding method x to future …
> Spp 9475 amend pipelines to allow rollback

- sml_builder/templates/help-methods-request.html
The details components contain heading mark-up which is mentioned in DAC_Details_Components_01. This heading mark-up is not recognisable by JAWS screen reading software but is discoverable by NVDA and this creates an illogical heading structure on the page for screen reader users as the heading levels skip from h3 to h2. This PR will amend the heading structure so that it follows a logical order on the page.
Code has not been commented and documentation has not been provided as it is not necessary for this PR.
**Testing**
Note when …
> SPP-9556-amend-illogical-heading-structure

- axeResults.json
- content/methods/ready-to-use-methods/thousand-pound-correction.jsonnet
- features/method_summary.feature
- features/steps/method_summary.py
The thousand pound correction method was missing the link to the method spec.
This ticket is to correct that.
Commenting and documentation changes not needed.
**Testing**
Usage …
> SPP-10585-add-method-spec-to-tpc

- terraform/cloudfront.tf
During a rebase some changes were undone.
This Pr is to address the issue
**Testing**
Usage
E.G feat: adding method x to future methods table
fix: A bug fix
E.G fix: amending page …
> feat:SPP-10641-deploy-preprod-and-prod

- terraform/cloudfront.tf
Added missing sha256 code for dev
**Testing**
Usage
E.G feat: adding method x to future methods table
fix: A bug fix
E.G fix: amending page for method x to show correct release …
> fix: Spp 10641 deploy preprod and prod

- terraform/cloudfront.tf
Added missing sha256 code
**Testing**
Usage
E.G feat: adding method x to future methods table
fix: A bug fix
E.G fix: amending page for method x to show correct release version …
> Spp 10641 deploy preprod and prod

- axeResults.json
- content/methods/ready-to-use-methods/totals-and-components.jsonnet
The TAC specification link needs changing.
It has been updated to match the new infrastructure of the specifications repo.
**Testing**
Usage
E.G feat: adding method x to future …
> feat:SPP-10744-correct-tac-link

- sml_builder/templates/about.html
- sml_builder/templates/help-methods-request.html
- sml_builder/templates/help.html
- sml_builder/templates/help_category.html
- sml_builder/templates/sidebar.html
Amending Page layout of sidebar pages, all element should be contained with in the 12 column grid, previous sidebar calculation did not account for the 1 column "push" so sidebar spilled into a column 13 outside of the grid
**Testing**
Usage
BREAKING CHANGE: any change that breaks current functionality and may cause compatibility errors to …
> SPP-10352 Amending Sidebar to correctly allign elements within 12 column grid

- content/glossary/baw.jsonnet
- features/help_center.feature
- features/steps/help-centre.py
- sml_builder/templates/help-methods-request.html
The methods summary page and glossary pages both contain references to BAW which are no longer relevant. The set of instructions on the method summary page relating to BAW also contains sensory descriptions e.g. "[...] click the three horizontal lines at the top left corner of the screen." These descriptions are a level A accessibility issues as they may confuse visually impaired users.
BAW is no longer relevant to the methods library catalogue so this PR will remove any references to it.
Code has not been commented and documentation has not been provided as this is not necessary for this pull request.
**Testing**
tags and will copy this …
> SPP-9448-remove-BAW-references

- content/methods/future-methods/cell-key-perturbation.jsonnet
- features/accessibility.feature
- features/method_summary.feature
- features/methods.feature
This pull request adds cell key perturbation to the list of future methods.
Code has not been commented and documentation has not been provided as it is not necessary for this PR.
**Testing**
Usage …
> SPP-9319-add-cell-key-perturbation

- config/README.md
- config/feature.json
- sml_builder/__init__.py
- sml_builder/templates/index.html
- sml_builder/utils.py
This pull request introduces the ability for a developer to 'option' pieces of code that they may be working on, i.e. control whether certain pieces of code are activated or deactivated by editing a single config file.
**Testing**
Usage
E.G feat: …
> SPP-10835-introduce-code-optioning

- ci/dev-pipeline.yml
- ci/live-pipeline.yml
During dependabot amendments init_metadata.sh was integrated into the steps that need it, however on destroy-terraform it still attempts to run it as a separate step that causes failures
**Testing**
Usage
E.G BREAKING CHANGE: refactored method x to take variable y as input (changed from …
> Destroy Terraform Fix

- sml_builder/cms.py
- sml_builder/glossary.py
- sml_builder/utils.py
This pull request fixes an issue where a file regarding the content management system was not correctly disabled, causing some issues with localhost. 
Code has not been commented and documentation has not been provided since it is not necessary for this pull request.
**Testing**
Usage
E.G …
> SPP-11063-option-cms.py

- ci/dev-pipeline.yml
- ci/live-pipeline.yml
- ci/tasks/terraform/apply_terraform.sh
- ci/tasks/terraform/destroy_terraform.sh
Issue noticed with destroy terraform, aws_account_id terraform variable is required for the terraform plan to run. This PR exports that variable to make it available within the CI run
**Testing**
- [] For a change that needs to be deployed in a release I have a commit with the fix:, feat: or BREAKING CHANGE:
Usage
BREAKING CHANGE: any change …
> Amending Destroy_terraform to include required tf variables

- sml_builder/templates/methods.html
This pull request updates the future methods table so that when no future methods are present, the 'no search results' description no longer shows. This is a bug as the 'no search results' description should only show when the search feature is enabled in the feature.json file.
Future methods table before code alteration:
Future methods table after code alteration:
Code has not been commented and documentation has not been updated since it is not necessary for this pull request.
**Testing**
Note when merging, squash commit must begin …
> SPP-11416-update-furutre-methods-table

- .github/workflows/contenful-push.yml
Creates a github actions pipeline that amends CONTENFUL_CHANGELOG.md when triggered via a webhook
- [] Code to be commented on where applicable 
- [] Documentation updated where required 
**Testing**
Usage
E.G BREAKING CHANGE: …
> Create Github Action for Contentful workflow changes

- CMS.md
- ci/dev-pipeline.yml
- ci/live-pipeline.yml
- ci/tasks/build_and_deploy/build_files.sh
- config/README.md
- config/feature.json
- sml_builder/cms.py
This pull request updates the code to be compatible with the new content management system space. There are now three separate keys which have access only to their respective prod, preprod and dev environments in contentful. 
**Testing**
Usage
E.G BREAKING CHANGE: refactored method x to take …
> SPP-11336-update-contentful-keys

- sml_builder/api_reference.py
- sml_builder/help_centre.py
- sml_builder/utils.py
This pull request fixes a minor bug highlighted when preparing for the help centre demo for the Content Management System. 
The issue was discovered when attempting to move a help centre subcategory into a different category using the Help Centre Structure JSON in Contentful. The table of contents in the help centre would be correctly updated, however clicking through to the subcategory page would result in a 404 error.
This was due to an issue with the guidances method; within this method the category_labels method was always being called with the local help_centre.json file path rather than using the help centre structure from the CMS. 
The category_labels method was also restructured to expect a dictionary type rather than a file path to the dictionary, since the content dictionary …
> rewrite contents_helper for compatibility with CMS

- ci/live-pipeline.yml
- config/feature.json
- pyproject.toml
- sml_builder/templates/cms/method_macro.html
Make necessary changes for the CMS end to end demo
**Testing**
Usage
E.G feat: adding method x to future methods …
> Cms end to end demo

- ci/live-pipeline.yml
This pull request updates the Contentful environment keys that are used in the pipeline to match the same environment as the CONTENTFUL_ENVIRONMENT variable. These were not consistently updated when the CONTENTFUL_ENVIRONMENT variables were updated previously, leading to 404 errors i.e. 'environment not found' since each key is only able to access its assigned environment.
Code has not been commented and documentation has not been updated since it is not necessary for this pull request.
**Testing**
- [] For a change that needs to be deployed in a release I have a commit with the fix:, feat: or BREAKING CHANGE:
tags and will copy this commit …
> assign correct environment keys

- features/steps/method.py
- sml_builder/method.py
Deleting methods using the content management system occasionally causes a bug in freeze.py. This is due to the display_search_results method in methods.py not being compatible with the Content Management system, despite the fact that the method search feature is not currently enabled. Flask still attempts to generate the relevant URLs for the display_search_results method anyway, but these URLs are based off the .jsonnet method files rather than the methods in the CMS, resulting in invalid URLs.
**Testing**
Note when merging, squash …
> Fix bug when deleting methods in the CMS

- scripts/update_changelog.sh
This pull request corrects some syntax errors in the update_changelog shell script
**Testing**
Usage
E.G feat: …
> Fix syntax in update_changelog.sh

- scripts/update_changelog.sh
This pull request fixes a small typo and records the user ID when an entry is deleted in contentful.
**Testing**
Usage
feat: A new …
> SPP-19950-fix-update_changelog.sh

- sml_builder/templates/cms/methods_macro.html
This pull request updates the methods_macro for the content management system to comply with a newer version of the ONS design system.
**Testing**
Usage
E.G feat: adding method x …
> SPP-12008-fix-ons-status-label

- sml_builder/method.py
- sml_builder/templates/cms/method_macro.html
- sml_builder/templates/method.html
Github resource links replaced with a single list field that allows links in both a normal URL and Markdown style url format.
Users can now have any number of links at the bottom of a method page, when no links exist there is also no header for the external links
**Testing**
Usage
E.G BREAKING …
> Amending method to read new external links list

- CMS.md
- ci/dev-pipeline.yml
- ci/live-pipeline.yml
- features/method_summary.feature
- features/steps/method_summary.py
- scripts/contentful_Audit.sh
- scripts/contentful_migrate.sh
- scripts/contentful_rollback.sh
- scripts/sub_scripts/deletion_changeset.py
- scripts/update_changelog.sh
Update to remove any reference to contentful dev environment so that it can be removed ahead of the contentful update. 
**Testing**
Usage
E.G BREAKING CHANGE: refactored method x to take variable y as input (changed from variable …
> SPP-12644 remove dev CMS environment references
