content/help_centre/help_centre.json
content/other/help-pages.jsonnet

Description:
This story is about removing superfluous question marks in the help centre and in the click through page associated with each link.

spp-7695 remove question marks

---

content/glossary/expert-group.jsonnet

Description:
This story is about changing the link in the glossary that points to further information about Expert Groups. 
It currently points to https://analysisfunction.civilservice.gov.uk/government-statistical-service-and-statistician-group/gss-support/methodology/information-on-specific-methods/#analysis
It needs to change to point to 
[Information on specific statistical methods – Government Analysis Function (civilservice.gov.uk)](https://analysisfunction.civilservice.gov.uk/government-statistical-service-and-statistician-group/gss-support/methodology/information-on-specific-methods/) (i.e. not to the header within the page).

spp-7696 change hyperlink to expert groups

---

sml_builder/templates/methods.html

Description:
This story is about changing internal methods line as follows:
On: https://d1jgbw8ee9pybj.cloudfront.net/methods, in the grey box describing private/internal/public methods, change
Internal methods’ access can be requested by ONS employees via their ONS Digital GitHub account
TO
Internal methods can be accessed on request by ONS employees via their ONS Digital GitHub account
(Reason for this change: poor grammar/use of apostrophe, wording brings sentence in line with other lines in box)

spp-7707 change internal methods line

---

sml_builder/templates/methods.html

https://jira.ons.gov.uk/browse/SPP-8330
Private method permissions text updated to specify ONS staff only
Disclaimer about new methods becoming available added to bottom of page
glossary link updated

Methods catalogue amended

---

sml_builder/templates/content/privacy.html

Updating the Privacy Page to reference the correct URL
This was noticed during a review of the website content
Associated ticket: [SPP-8363](https://jira.ons.gov.uk/browse/SPP-8363)

SPP-8363 Update Privacy page to reference the correct URL

---

features/help_center.feature
features/steps/help-centre.py
sml_builder/templates/help-methods-request.html
sml_builder/templates/help_category.html

The help center sub categories do not have a back link present unlike the method summary pages. This ticket is to add them in.
**Testing**
**Deployment**

SPP-8455-add-back-link-to-help-centre

---

content/help_centre/help_centre.json
features/steps/help-centre.py
features/steps/setupSelenium.py

Find and view methods link moved to access (and usage) section of the help center (originally was in information section at top of page). Behave tests amended in-line with this change

SPP-8526-Move-View-Methods-To-Access-Section

---

sml_builder/templates/cookies.html

Collapsible component on cookies page was misaligned
Cause of the issue was an unintended interaction with div tags that encapsulated the call to the component. Use of titleTag variable fixes the issue
Jira Ticket: https://jira.ons.gov.uk/browse/SPP-8545
**Testing**

Spp-8545-fix-cookies-misallignment

---

ci/live-pipeline.yml
ci/tasks/build_and_deploy/build_files.sh

Fix: adding in git credentials to the pipeline as the basic git resource doesn't set these, whereas the PR resource did

SPP-9387-semantic-release-fix

---

ci/dev-pipeline.yml
ci/live-pipeline.yml

CI fix to add in the new gpg verification key for signed commits from the concourse pipeline to allow semantic release automation
**Testing**

ci: adding in  commit verification keys for signed commits

---

sml_builder/templates/core.html

The page titles do not include the name of the service provider. This pull request ensures the page title contains the service name. This will enable screen reader users to identify the which service they are navigating.
**Testing**

SPP-9552-amend-page-title

---

features/accessibility.feature
features/help_center.feature
features/steps/generic.py
sml_builder/templates/help-methods-request.html
sml_builder/templates/help_category.html

This pull request is to amend the duplicated page titles and headings across multiple pages in the help centre. This will make it easier for screen reader users to distinguish between each of the pages.
**Testing**

SPP-9446-rename-duplicate-page-titles

---

ci/live-pipeline.yml
ci/tasks/testing/run_bdd_tests.sh
features/methods.feature

When running the BDD tests for the sml-catalogue repo, and the tests fail in the concourse pipeline, GitHub checks still pass and let you merge the dev branch to the main.
run_bdd_tests.sh file updated to fix this issue.
Documentation & code comments are not necessary in this instance.
**Testing**

SPP-9996 Concourse Pipeline False Pass Fix

---

features/help_center.feature
sml_builder/templates/help-methods-request.html

The text on the drop down 'I am a user from outside the ONS' on the help center method request page, is difficult to read as the blocks of text don't start on separate lines, this PR will break up the blocks of text.
No comments or documentation  added as it wasn't needed for this specific PR
**Testing**

SPP-10170-break-up-box-of-test

---

sml_builder/templates/glossary.html

When users activate the ‘Skip to main content’ link the focus shift to the main content as expected but if the users continue to navigate using the tab key, focus is placed on the ‘Back to top’ button and then to the alphabetical links inside the main content. This creates an illogical focus order and may be problematic for keyboard only and screen reader users.
This PR will ensure that the 'Back to top' button is correctly positioned so that the page has a logical focus order.
Code has not been commented and documentation has not been provided because it is not necessary for this PR.
**Testing**

SPP-9540-amend-focus-order

---

pyproject.toml

Part of [SPP-10242's pull request](https://github.com/ONSdigital/sml-python-small/pull/67).
This PR fixes an compatibility issue between black and isort by ensuring that isort uses the 'black' profile.
Code has not been commented and documentation has not been provided since it is not necessary for this PR.
**Testing**

SPP-10242-update-catalogue-pytools-file

---

.github/pull_request_template.md

Rule changes added to require one of the semantic versioning tags in order to complete a pr, amendments to the PR template to remind users of these tags
**Testing**
commit message

docs: amending pr template to show required tags

---

ci/tasks/build_and_deploy/deploy.sh
ci/tasks/build_and_deploy/deploy.yml

Amendments to the Concourse pipeline to automatically invalidate all caches on the deployed cloudfront instance during CI/CD execution, allowing users to see updates to deployment environments immediately after deployment and no longer need to wait for the cache to expire/manually invalidate the cache
**Testing**
Usage
BREAKING CHANGE: any …

SPP-10758 Invalidate Cloudfront Cache During Deployment 

---

.github/workflows/contentful-update.yml
scripts/update_changelog.sh

Pass the environment variable so that the API looks at the correct environment for changes.
**contentful-update.yml**
- Pass through the "preprod" value to update_changelog.sh
**update_changelog.sh**
- Check the env variable is passed to the script
- Use passed value in the API call to get_entry_by_id()

Pass env to CMS Changelog Script

---

deployment_role_bootstrap/role.tf

Adding listtags to lambda function, AWS discovered a bug where the GetFunction permission inherited the listtags permission when it shouldn't, this will be patched next month which will cause errors if we use the listtags api

adding list tags to lambda role

---

ci/tasks/util/send_email.py
sml_builder/__init__.py

Send_email.py error'd out when the build process failed, this has been fixed to correctly send the email. Additionally. Freeze.py should no longer error if it finds a 404 page (this can happen as freeze.py creates a manifest of all expected links when its run and attempts to access them. however as pages are edited and deleted on contentful these expected links can causes issues as local files can add to the expected manifest list, even though local files are not used in the build.

Fixing issues with Email and 404 error with contentful

---

pyproject.toml

Poetry was failing as due to poetry 2.0 update our project name was now wrong (project should be a subfolder from where the pyproject is, not the current directory)

Fixing pyproject to use correct package name
